networks:
  halmark_network:
    external: true

services:
  auth_spa:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - RUST_LOG=info
    command: [ "trunk", "serve", "--address", "0.0.0.0", "--port", "3001" ]
    networks:
      - halmark_network
