AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.13

  SAM Template for backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowOrigin: !Sub "'${CorsAllowedOrigin}'"
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,Cookie'"
      AllowCredentials: true

# Parametersセクションは、デプロイ時に指定可能な入力パラメータを定義します
Parameters:
  Environment:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - stg
      - prd
    Description: Deployment environment
  Domain:
    Type: String
    Default: App Domain
  ReduirectPath:
    Type: String
    Description: Redirect URI
  CorsAllowedOrigin:
    Type: String
    Default: halal.local
    Description: Allowed origin for CORS
  CognitoUserPoolId:
    Type: String
    Description: Cognito User Pool ID
  CognitoAppClientId:
    Type: String
    Description: Cognito App Client ID
  CognitoAppClientSecret:
    Type: String
    Description: Cognito App Client Secret

Resources:
  # Lambda関数が実行時に利用するIAMロールを定義します
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "halmark-${Environment}-lambda-role"  # ロール名を環境ごとに設定
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com  # Lambdaサービスがこのロールを引き受けることを許可
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaLoggingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: CognitoAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:SignUp
                  - cognito-idp:ConfirmSignUp
                  - cognito-idp:ResendConfirmationCode
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:AdminRespondToAuthChallenge
                  - cognito-idp:AdminSetUserPassword
                Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"

  # SingupFunctionは、AWS Lambda関数を定義します
  SignupFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "halmark-${Environment}-signup" # Lambda関数名を環境ごとに設定
      Description: !Sub "[halmark][${Environment}] Signup 関数"
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn  # 実行ロールを設定
      Events:
        Signup:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/signup
            Method: post
      Environment:
        Variables:
          ENV: !Ref Environment
          COGNITO_APP_CLIENT_ID: !Ref CognitoAppClientId
          COGNITO_APP_CLIENT_SECRET: !Ref CognitoAppClientSecret
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app/signup
      DockerTag: python3.13-v1

  # SignupConfirmFunctionは、AWS Lambda関数を定義します
  SignupConfirmFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "halmark-${Environment}-signup-confirm" # Lambda関数名を環境ごとに設定
      Description: !Sub "[halmark][${Environment}] Signup Confirm 関数"
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn  # 実行ロールを設定
      Events:
        SignupConfirm:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/signup/confirm
            Method: post
      Environment:
        Variables:
          ENV: !Ref Environment
          COGNITO_APP_CLIENT_ID: !Ref CognitoAppClientId
          COGNITO_APP_CLIENT_SECRET: !Ref CognitoAppClientSecret
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app/signup_confirm
      DockerTag: python3.13-v1

  # ResendCodeFunctionは、AWS Lambda関数を定義します
  ResendCodeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "halmark-${Environment}-resend-code" # Lambda関数名を環境ごとに設定
      Description: !Sub "[halmark][${Environment}] Resend Code 関数"
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn  # 実行ロールを設定
      Events:
        SignupConfirm:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/resend-code
            Method: post
      Environment:
        Variables:
          ENV: !Ref Environment
          COGNITO_APP_CLIENT_ID: !Ref CognitoAppClientId
          COGNITO_APP_CLIENT_SECRET: !Ref CognitoAppClientSecret
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app/resend_code
      DockerTag: python3.13-v1

  # SigninFunctionは、AWS Lambda関数を定義します
  SigninFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "halmark-${Environment}-signin" # Lambda関数名を環境ごとに設定
      Description: !Sub "[halmark][${Environment}] Signin 関数"
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn  # 実行ロールを設定
      Events:
        Signin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/signin
            Method: post
      Environment:
        Variables:
          ENV: !Ref Environment
          COGNITO_APP_CLIENT_ID: !Ref CognitoAppClientId
          COGNITO_APP_CLIENT_SECRET: !Ref CognitoAppClientSecret
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app/signin
      DockerTag: python3.13-v1

  # MfaVerifyFunctionは、AWS Lambda関数を定義します
  MfaVerifyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "halmark-${Environment}-mfaverify" # Lambda関数名を環境ごとに設定
      Description: !Sub "[halmark][${Environment}] MFA Verify 関数"
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn  # 実行ロールを設定
      Events:
        Signin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/mfa
            Method: post
      Environment:
        Variables:
          ENV: !Ref Environment
          DOMAIN: !Ref Domain
          REDIRECT_PATH: !Ref ReduirectPath
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_APP_CLIENT_ID: !Ref CognitoAppClientId
          COGNITO_APP_CLIENT_SECRET: !Ref CognitoAppClientSecret
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app/mfa_verify
      DockerTag: python3.13-v1

  ForgotPasswordFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "halmark-${Environment}-forgot-password" # Lambda関数名を環境ごとに設定
      Description: !Sub "[halmark][${Environment}] Forgot Password 関数"
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn  # 実行ロールを設定
      Events:
        Signin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/forgot-password
            Method: post
      Environment:
        Variables:
          ENV: !Ref Environment
          COGNITO_APP_CLIENT_ID: !Ref CognitoAppClientId
          COGNITO_APP_CLIENT_SECRET: !Ref CognitoAppClientSecret
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app/forgot_password
      DockerTag: python3.13-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SignupApi:
    Description: API Gateway endpoint URL for Signup function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/auth/signup"
  SignupConfirmApi:
    Description: API Gateway endpoint URL for Confirm Signup function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/auth/signup/confirm"
  ResendCodeApi:
    Description: API Gateway endpoint URL for Resend Code function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/auth/resend-code"
  SigninApi:
    Description: API Gateway endpoint URL for Signin function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/auth/signin"
  MfaVerifyApi:
    Description: API Gateway endpoint URL for Mfa verify function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/auth/mfa"
  ForgotPasswordApi:
    Description: API Gateway endpoint URL for Forgot Password function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/auth/forgot-password"
  SignupFunction:
    Description: Signup Lambda Function ARN
    Value: !GetAtt SignupFunction.Arn
  SignupConfirmFunction:
    Description: Confirm Signup Lambda Function ARN
    Value: !GetAtt SignupConfirmFunction.Arn
  ResendCodeFunction:
    Description: Signup Lambda Function ARN
    Value: !GetAtt ResendCodeFunction.Arn
  SigninFunction:
    Description: Signin Lambda Function ARN
    Value: !GetAtt SigninFunction.Arn
  MfaVerifyFunction:
    Description: Signin Lambda Function ARN
    Value: !GetAtt MfaVerifyFunction.Arn
  ForgotPasswordFunction:
    Description: Signin Lambda Function ARN
    Value: !GetAtt ForgotPasswordFunction.Arn